name: PyPi Release 

on:
  push:
    tags:        
      - 'v*'    


jobs:
  pypi_package_deploy:
      runs-on: ubuntu-20.04
      steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.9 
            uses: actions/setup-python@v2
            with:
                python-version: 3.9 
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install flake8 pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          - name: Build
            run: |
                make dist
          - name: Publish package
            # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
            if: startsWith(github.ref, 'refs/tags')
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}

